### ISSUE TITLE
Attempting to use absolute fees in send transaction fails

### ISSUE THREAD

**Issue by thunderbiscuit** [LLFourn/gun#2]
The `help` output for `gun send` indicates that one can use `abs:300` to define the absolute number of sats for the fee
```sh
ARGS:
    <value>    The amount to send with denomination e.g. 0.1BTC
    <to>       The address to send the coins to
    <fee>      The transaction fee to attach e.g. spb:4.5 (4.5 sats-per-byte), abs:300 (300 sats absolute fee), in-
               blocks:3 (set fee so that it is included in the next three blocks) [default: in-blocks:1]
```

but attempting to build a transaction using absolute amount returns the following error:
```sh
❯ gun send 0.0001BTC mkHS9ne12qx9pS9VojpwU5xtRd4T7X7ZUt abs:300
error: Invalid value for '<fee>': unknown denomination:
```
Is there supposed to be a denomination there if we want to use straight sats? I tried `SAT` but it didn't work. Of course simply defining it in BTC did work. Just wondering if sats are an option, as per the help note.

Related to this: the note for `<value> explains one is required to provide a denomination, and one example is provided. It feels like there may be others but we're left wondering what they are. Are they listed anywhere else in the help?

**Comment by LLFourn** [comment]
Thanks `sat` should work but I thought I had done it so without any denomination it would assume sats. To be fixed.

**Comment by thunderbiscuit** [comment]
Yep I just confirmed that `sat` works. Thanks.
